repos:
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.770
    hooks:
    - id: mypy
      args: ["--strict-equality", "--disallow-any-generics", "--disallow-untyped-defs", "--allow-redefinition", "--ignore-missing-imports"]